[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "weHateTP"
version = "1.4.0"
description = "TypeBot + PyPI OIDC + inject – By DarkFox"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [{name = "DarkFox"}]
dependencies = ["PyYAML>=6.0"]

[project.scripts]
weHateTP = "weHateTP.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["weHateTP*"]
